german_cabinets <- list(
  "Adenauer I" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4640"
  , "Adenauer II" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4641"
  , "Adenauer III" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4642"
  , "Adenauer IV" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4643"
  , "Adenauer V" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4644"
  , "Adenauer VI" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4645"
  , "Adenauer VII" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4646"
  , "Adenauer VIII" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4647"
  , "Adenauer IX" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4648"
  , "Erhard I" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4649"
  , "Erhard II" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4650"
  , "Kiesinger" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4651"
  , "Brandt I" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4652"
  , "Brandt II" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4653"
  , "Scheel (acting)" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4654"
  , "Schmidt I" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4655"
  , "Schmidt II" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4656"
  , "Schmidt III" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4657"
  , "Schmidt IV" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4658"
  , "Kohl I" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4659"
  , "Kohl II" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4660"
  , "Kohl III" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=4661"
  , "Kohl IV" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3930"
  , "Kohl V" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3931"
  , "Schröder I" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3932"
  , "Schröder II" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3933"
  , "Merkel I" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3934"
  , "Merkel II" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3935"
  , "Merkel III" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3936"
  , "Merkel IV" = "https://whogoverns.eu/cabinets?view=gabinete&gabinete=3937"
)

usethis::use_data(german_cabinets, german_cabinets, overwrite = TRUE)
